services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        EzSystems\EzPlatformAdminUi\Form\TrashLocationOptionProvider\TrashLocationOptionProvider:
            tags: ['ezplatform.form.trash_location_option']

    EzSystems\EzPlatformAdminUi\Form\SubmitHandler: ~

    EzSystems\EzPlatformAdminUi\Form\Factory\:
        resource: '../../../lib/Form/Factory'

    EzSystems\EzPlatformAdminUi\Form\DataMapper\:
        resource: '../../../lib/Form/DataMapper'

    EzSystems\EzPlatformAdminUi\Form\Type\:
        resource: '../../../lib/Form/Type'

    EzSystems\EzPlatformAdminUi\Form\EventListener\:
        resource: '../../../lib/Form/EventListener'

    EzSystems\EzPlatformAdminUi\Form\TrashLocationOptionProvider\:
        resource: '../../../lib/Form/TrashLocationOptionProvider'

    EzSystems\EzPlatformAdminUi\Form\TrashLocationOptionProvider\OptionsFactory:
        arguments: [!tagged ezplatform.form.trash_location_option]

    EzSystems\EzPlatformAdminUi\Form\Type\Extension\Content\ContentEditTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: EzSystems\RepositoryForms\Form\Type\Content\ContentEditType }

    EzSystems\EzPlatformAdminUi\Form\Type\Policy\PolicyChoiceType:
        arguments:
            $policyMap: "%ezpublish.api.role.policy_map%"

    EzSystems\EzPlatformAdminUi\Form\Type\Content\Draft\ContentCreateType:
        arguments:
            $contentTypeChoiceLoader: '@EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\ContentTypeChoiceLoader'
            $languageChoiceLoader: '@EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\LanguageChoiceLoader'

    EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\ContentTypeChoiceLoader: ~

    EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\LanguageChoiceLoader:
        arguments:
            $configResolver: "@ezpublish.config.resolver"

    EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\ConfiguredLanguagesChoiceLoader:
        arguments:
            $configResolver: "@ezpublish.config.resolver"

    EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\PermissionAwareContentTypeChoiceLoader:
        arguments:
            $decorated: '@EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\ContentTypeChoiceLoader'
            $module: 'content'
            $function: 'create'

    EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\PermissionAwareLanguageChoiceLoader:
        arguments:
            $decorated: '@EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\LanguageChoiceLoader'
            $module: 'content'
            $function: 'create'

    EzSystems\EzPlatformAdminUi\Form\Extension\RichTextTypeExtension:
        public: true
        tags:
            - { name: form.type_extension, extended_type: EzSystems\EzPlatformRichText\Form\Type\RichTextType }

    EzSystems\EzPlatformAdminUi\Form\Extension\HelpMultilineMessageExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    EzSystems\EzPlatformAdminUi\Form\TrashLocationOptionProvider\HasReverseRelations:
        tags:
            - { name: 'ezplatform.form.trash_location_option', priority: 100 }

    EzSystems\EzPlatformAdminUi\Form\TrashLocationOptionProvider\HasChildren:
        tags:
            - { name: 'ezplatform.form.trash_location_option', priority: 80 }

    EzSystems\EzPlatformAdminUi\Form\TrashLocationOptionProvider\HasUniqueAssetRelation:
        tags:
            - { name: 'ezplatform.form.trash_location_option', priority: 60 }

    EzSystems\EzPlatformAdminUi\Form\TrashLocationOptionProvider\HasAssetRelation:
        tags:
            - { name: 'ezplatform.form.trash_location_option', priority: 40 }
